version: "3.9"
services:

  web: 
    container_name: mywebserver
    image: nginx
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./mosquitto/keys/server.crt:/etc/nginx/certs/server.crt  
      - ./mosquitto/keys/server.key:/etc/nginx/certs/server.key 
    ports:
        - "8080:80"
        - "443:443"
    
  mqtt:
    container_name: myqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/keys/server.crt:/mosquitto/keys/server.crt
      - ./mosquitto/keys/server.key:/mosquitto/keys/server.key 
    ports:
        - "1883:1883"
        - "1884:1884"

# https://hub.docker.com/_/eclipse-mosquitto